services:
  - type: web
    name: my-journal-app
    env: python
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        value: your-super-secret-key
        sync: false
      - key: APP_PASSWORD
        value: your-secret-password
        sync: false
      - key: GF_PASSWORD
        value: aaduaadu
        sync: false
